### ISSUE TITLE
Med-Flamingo Code

### ISSUE THREAD

**Issue by HuichiZhou** [richard-peng-xia/CARES#1]
Hi, I want to inquire about can you share us the code of Med-Flamingo? I want to test the VQA.

**Comment by richard-peng-xia** [comment]
Hi, @HuichiZhou.

Thanks for your interest in CARES.

You can refer to the official code of [Med-Flamingo](https://github.com/snap-stanford/med-flamingo), which is the basis for our evaluation as well.
