### ISSUE TITLE
Regarding Evaluation Procedure

### ISSUE THREAD

**Issue by k-m-irfan** [richard-peng-xia/CARES#2]
Hi, can you please give a detailed evaluation procedure to replicate the tables/results from the paper?

**Comment by richard-peng-xia** [comment]
Hi @k-m-irfan,

Please refer to the instructions in `README.md`.

To be more specific, you can follow this:

```
1. Download the datasets
2. Prepare the data in the required JOSNL format (for different tasks)
3. Set up the evaluation models
4. Evaluate the results based on the corresponding metrics
```

Feel free to ask me if you have any questions.

**Comment by russellyq** [comment]
> Hi [@k-m-irfan](https://github.com/k-m-irfan),
> 
> Please refer to the instructions in `README.md`.
> 
> To be more specific, you can follow this:
> 
> ```
> 1. Download the datasets
> 2. Prepare the data in the required JOSNL format (for different tasks)
> 3. Set up the evaluation models
> 4. Evaluate the results based on the corresponding metrics
> ```
> 
> Feel free to ask me if you have any questions.

Hi @richard-peng-xia ，

I am still confused about the evaluation process. Can you be more clear about this ?

For example, which file as the gt and which file as prompt to inference the model to get the prediction.

Thanks.

**Comment by russellyq** [comment]
Hi @richard-peng-xia ,

I am still confused about the evaluation process. Can you be more clear about this ?

For example, which file as the gt and which file as prompt to inference the model to get the prediction.

Thanks.
